### ISSUE TITLE
Help with IOS key insertion

### ISSUE THREAD

**Issue by codyboaz** [nickcoury/nativescript-maps-app#2]
Hey Nick thanks for the maps/angular2/Nativescript repo! I had a quick question. I am new to Nativescript. I have figured out where to put my API key for Android at app/App_Resources/Android/values/nativescript_google_maps_api.xml

But dont know how to add it correctly to IOS in the

app/app.component.ts

file. 

Could you please offer some assistance? Thanks!

**Comment by nickcoury** [comment]
It looks like you figured it out, if you have any questions let me know!

**Comment by codyboaz** [comment]
Hey Nick I did figure it out. However I now have another issue maybe you can help with. When I run my project it works without any issues on IOS, yet on Android it will run but the map does not get painted. It only shows a tan screen with the Google logo on the bottom left. Any idea what the issue may be?

**Comment by nickcoury** [comment]
That is often an API Key issue.  Double check that you have a Google Maps SDK Android key (not reusing an iOS key), and that it's in the right place.

Otherwise it could be a connectivity issue if it can't download the maps.

If neither of those are it, I would debug looking at the Android Logcat output, which may show an error of what's failing.
