### ISSUE TITLE
TypeScript compiler failed with exit code 1

### ISSUE THREAD

**Issue by salman15** [nickcoury/nativescript-maps-app#4]
I've followed the instructions explained and have the newest versions of TS and NS, but I'be been running in to this error for hours.

Whats the cause of it?

![image](https://cloud.githubusercontent.com/assets/24669227/21487125/5a374dc8-cbc2-11e6-936c-092e8394fcb2.png)

![image](https://cloud.githubusercontent.com/assets/24669227/21487122/45070a4c-cbc2-11e6-883f-74fba7d8c680.png)

**Comment by nickcoury** [comment]
Those are Typescript errors.  I'm unable to reproduce, even with Typescript 2.1.4 so I'm not sure what's going on.  Your global Typescript settings may be different or more strict than mine.

You can try changing `"noEmitOnError": true` to `"noEmitOnError": false` in `tsconfig.json`, which will ignore the Typescript errors since it looks like those are just missing or improper definitions in the node libraries.

**Comment by salman15** [comment]
@nickcoury Thank you very mutch! your answer has solved my solution! Thanks again and a happy new year!
